<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <title>ondeficar table</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Mono' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="reset.css">
        <link rel="stylesheet" href="styles.css">
    </head>
    <body>        
        <div class="header">
            <div class="room-type-hdr"><div class="collapse"></div>room types</div>
            <div class="month-page">
                <?php for ($i=0;$i<365;$i++):?>
                <div class="date">mon <?php print $i?></div>
                <?php endfor?>
            </div>
        </div>
        <div class="wrapper">             
            <div class="aside">                
                <?php for ($i=0;$i<100;$i++):?>
                <div class="room-type">
                    <div class="room-type-collapse"><div class="collapse open"></div><span><big>Suite <?php print $i?></big><small>800 Rooms</small></span></div>
                    <div class="condition">Available For Sale</div>
                    <div class="condition">Remaining Inventory</div>
                    <div class="condition">Rate</div>
                    <div class="condition">Min LOS</div>
                    <div class="condition">Max LOS</div>
                    <div class="condition">Accommodation Blocked</div>
                    <div class="condition">Closed to Arrival</div>
                    <div class="condition">Closed to Departure</div>
                </div>
                <?php endfor?>
                <!--<div class="room-type">
                    <div class="room-type-collapse grey"><div class="collapse"></div><span><big>Queen with balcony</big><small>380 Rooms</small></span></div>
                    <div class="condition grey">Available For Sale</div>
                    <div class="condition grey">Remaining Inventory</div>
                    <div class="condition grey">Rate</div>
                    <div class="condition grey">Min LOS</div>
                    <div class="condition grey">Max LOS</div>
                    <div class="condition grey">Accommodation Blocked</div>
                    <div class="condition grey">Closed to Arrival</div>
                    <div class="condition grey">Closed to Departure</div>
                </div>
                <div class="room-type">
                    <div class="room-type-collapse"><div class="collapse"></div><span><big>6-bed-dorm</big><small>1 Rooms</small></span></div>
                    <div class="condition">Available For Sale</div>
                    <div class="condition">Remaining Inventory</div>
                    <div class="condition">Rate</div>
                    <div class="condition">Min LOS</div>
                    <div class="condition">Max LOS</div>
                    <div class="condition">Accommodation Blocked</div>
                    <div class="condition">Closed to Arrival</div>
                    <div class="condition">Closed to Departure</div>
                </div>-->
            </div>
            <div class="wrap">
                <div class="page-wrap">
                    <?php for ($i=0;$i<100;$i++):?>
                    <div class="page">                        
                        <div class="empty"></div>
                        <div class="line">
                            <span class="cell available-sale">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span>
                        </div>
                        <div class="line undernone">
                            <span class="cell change">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span>
                        </div>
                        <div class="line">
                            <span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span>
                        </div>
                        <div class="line">
                            <span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span>
                        </div>
                        <div class="line">
                            <span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span>
                        </div>
                        <div class="line">
                            <span class="cell check-off change"></span><span class="cell check-on blocked"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span>
                        </div>
                        <div class="line">
                            <span class="cell check-on change"></span><span class="cell check-on"></span><span class="cell check-off"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span>
                        </div>
                        <div class="line">
                            <span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span>
                        </div>
                        <div class="empty grey"></div>
                        <div class="line grey">
                            <span class="cell available-sale">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span>
                        </div>
                        <div class="line grey undernone">
                            <span class="cell change">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span>
                        </div>
                        <div class="line grey">
                            <span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span>
                        </div>
                        <div class="line grey">
                            <span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span>
                        </div>
                        <div class="line grey">
                            <span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span>
                        </div>
                        <div class="line grey">
                            <span class="cell check-off"></span><span class="cell check-on blocked"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span>
                        </div>
                        <div class="line grey">
                            <span class="cell check-on"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span>
                        </div>
                        <div class="line grey">
                            <span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span>
                        </div>
                        <div class="empty"></div>
                        <div class="line">
                            <span class="cell available-sale">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span>
                        </div>
                        <div class="line undernone">
                            <span class="cell change">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span>
                        </div>
                        <div class="line">
                            <span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span>
                        </div>
                        <div class="line">
                            <span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span>
                        </div>
                        <div class="line">
                            <span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span>
                        </div>
                        <div class="line">
                            <span class="cell check-off"></span><span class="cell check-on blocked"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span>
                        </div>
                        <div class="line">
                            <span class="cell check-on"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span>
                        </div>
                        <div class="line">
                            <span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span>
                        </div>
                    </div>
                    <?php endfor?>
                    <!--<div class="page">
                        <div class="empty"></div>
                        <div class="line">
                            <span class="cell available-sale">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span>
                        </div>
                        <div class="line undernone">
                            <span class="cell change">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span>
                        </div>
                        <div class="line">
                            <span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span>
                        </div>
                        <div class="line">
                            <span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span>
                        </div>
                        <div class="line">
                            <span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span>
                        </div>
                        <div class="line">
                            <span class="cell check-off"></span><span class="cell check-on blocked"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span>
                        </div>
                        <div class="line">
                            <span class="cell check-on"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span>
                        </div>
                        <div class="line">
                            <span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span>
                        </div>
                        <div class="empty grey"></div>
                        <div class="line grey">
                            <span class="cell available-sale">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span>
                        </div>
                        <div class="line grey undernone">
                            <span class="cell change">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span>
                        </div>
                        <div class="line grey">
                            <span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span>
                        </div>
                        <div class="line grey">
                            <span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span>
                        </div>
                        <div class="line grey">
                            <span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span>
                        </div>
                        <div class="line grey">
                            <span class="cell check-off"></span><span class="cell check-on blocked"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span>
                        </div>
                        <div class="line grey">
                            <span class="cell check-on"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span>
                        </div>
                        <div class="line grey">
                            <span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span>
                        </div>
                        <div class="empty"></div>
                        <div class="line">
                            <span class="cell available-sale">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span>
                        </div>
                        <div class="line undernone">
                            <span class="cell change">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span><span class="cell">724</span>
                        </div>
                        <div class="line">
                            <span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span><span class="cell">R$ 100</span>
                        </div>
                        <div class="line">
                            <span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span><span class="cell">1</span>
                        </div>
                        <div class="line">
                            <span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span><span class="cell">0</span>
                        </div>
                        <div class="line">
                            <span class="cell check-off"></span><span class="cell check-on blocked"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span>
                        </div>
                        <div class="line">
                            <span class="cell check-on"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span><span class="cell check-on"></span>
                        </div>
                        <div class="line">
                            <span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span><span class="cell check-off"></span>
                        </div>
                    </div> -->
                </div>
            </div>
        </div>
    </body>
</html>
